# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

    app.admin_email: '%env(ADMIN_EMAIL)%'
    app.require_password: true
    app.languages: ['en', 'es', 'ca']

    app.portada_covers: 3

    app.pelicula_directory: '%env(APP_PELICULA_DIRECTORY)%'
    app.pelicula_directory.root: '%kernel.project_dir%/public/%app.pelicula_directory%'

    app.actor_directory: '%env(APP_ACTOR_DIRECTORY)%'
    app.actor_directory.root: '%kernel.project_dir%/public/%app.actor_directory%'

    app.user_directory: '%env(APP_USER_DIRECTORY)%'
    app.user_directory.root: '%kernel.project_dir%/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\FileService:
        arguments:
            $targetDirectory: '%app.pelicula_directory.root%'
